export type ADD_EMPLOYEE = 'ADD_EMPLOYEE';
export const ADD_EMPLOYEE = 'ADD_EMPLOYEE';

export type DELETE_EMPLOYEE = 'DELETE_EMPLOYEE';
export const DELETE_EMPLOYEE = 'DELETE_EMPLOYEE';

export type SEARCH_EMPLOYEES = 'SEARCH_EMPLOYEES';
export const SEARCH_EMPLOYEES = 'SEARCH_EMPLOYEES';

export type LOAD_EMPLOYEES = 'LOAD_EMPLOYEES';
export const LOAD_EMPLOYEES = 'LOAD_EMPLOYEES';